object Versions {

    const val compose = "1.3.3"
    const val composeMaterial = "1.3.1"
    const val composeCompiler = "1.4.3"
    const val lifecycle = "2.6.0"
    const val hilt = "2.45"
    const val hiltNavigation = "1.0.0"
    const val moshi = "1.14.0"
    const val retrofit = "2.9.0"
    const val okhttp3Logging = "4.10.0"
    const val junit = "4.13.2"
    const val mockitoKotlin = "4.1.0"
    const val androidPlugin = "7.4.2"
    const val kotlin = "1.8.10"
    const val coroutines = "1.6.4"
    const val viewmodelCompose = "2.6.0"
    const val javaInjectVersion = "1"
    const val navigation = "2.5.3"
    const val accompanist = "0.28.0"
    const val coil = "2.2.2"
    const val room = "2.5.0"
    const val gsmLocation = "21.0.1"

}